version: '3'
services:
  testsamlidp_idp:
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: opensearch-dashboards
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:5601/osd/_plugins/_security/saml/acs
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:5601/osd/_plugins/_security/saml/logout
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8080:8080"
    - "8443:8443"
    volumes:
      - ./config/authsources.php:/var/www/simplesamlphp/config/authsources.php
      - ./config-templates/authsources.php:/var/www/simplesamlphp/config-templates/authsources.php
      - ./metadata/saml20-idp-hosted.php:/var/www/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./metadata-templates/saml20-idp-hosted.php:/var/www/simplesamlphp/metadata-templates/saml20-idp-hosted.php